---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart sendry
  ansible.builtin.systemd:
    name: sendry
    state: restarted
  when: sendry_service_state == 'started'
